Adding notes and organNames
hubmapconsortium/ccf-asct-reporter pull request #229
Opened 2021-09-17 16:31 UTC by vutukuriajay2241

2021-09-17 16:56 UTC, bherr2 requested changes
A couple minor things, but otherwise fine

2021-09-17 16:56 UTC, bherr2 commented on projects/v2/src/app/actions/tree.actions.ts
> +  constructor(public AS_CT: number, public CT_B: number,  public AS_CT_organWise: object, public CT_B_organWise: object, public AS_AS?: number,public AS_AS_organWise?: object) {}
2 spaces => 1 space

2021-09-17 16:56 UTC, bherr2 commented on projects/v2/src/app/store/tree.state.ts
> +    AS_CT_organWise: object;
Tighten up types here. Should be `Record<string, number>` right?

2021-09-17 18:07 UTC, vutukuriajay2241 commented on projects/v2/src/app/actions/tree.actions.ts
> +  constructor(public AS_CT: number, public CT_B: number,  public AS_CT_organWise: object, public CT_B_organWise: object, public AS_AS?: number,public AS_AS_organWise?: object) {}
I didnt get this??

2021-09-22 15:59 UTC, bherr2 approved these changes

2021-09-22 16:00 UTC, merged