Adding hraVersion to Excel download
hubmapconsortium/ccf-asct-reporter pull request #645
Opened 2023-04-05 22:50 UTC by Knight7561

2023-04-06 13:54 UTC, bherr2 requested changes

2023-04-06 13:54 UTC, bherr2 commented on projects/v2/src/app/components/report/report.component.ts
> +        'tableVersion',
Table version does not need to be shown in the UI, only in the xlsx export.

2023-04-06 13:54 UTC, bherr2 commented on projects/v2/src/app/components/report/report.component.ts
> +        'tableVersion',
Column needs to be `table_version` and not `tableVersion`

2023-04-06 13:54 UTC, bherr2 commented on projects/v2/src/app/modules/root/root.component.ts
> +      const hraVersionFromQuery = query.get('hraVersions');
Why hraVersions? Let's talk before/after standup.

2023-04-17 20:12 UTC, pbrm4 commented on projects/v2/src/app/modules/root/root.component.ts
> +  extractNameFromFull(name: string) {
extractNameFromFull -> extractOrganNameFromFull

2023-04-19 12:13 UTC, bherr2 commented on projects/v2/src/app/components/report/report.component.ts
> +        'tableVersion',
I don't see any table_version string in your code. Can you explain?

2023-04-19 12:14 UTC, bherr2 commented on projects/v2/src/app/components/report/report.component.ts
> +        'tableVersion',
Also, I made a big oops. It IS actually supposed to be `tableVersion` in the sheets. Not sure if that was a change on the humnanatlas.io site or I just totally flubbed it. My bad. Please change back to `tableVersion`.

2023-04-26 18:38 UTC, pbrm4 commented on projects/v2/src/app/modules/root/root.component.html
Does this file have any changes? Looks like it has only formatting changes

2023-04-26 21:27 UTC, Knight7561 commented on projects/v2/src/app/modules/root/root.component.html
YEAH

2023-05-01 18:05 UTC, merged